services:
  - type: web
    name: trading-predictor
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false   # ставиш свій токен у Render Dashboard
      - key: COINMARKETCAP_API_KEY
        sync: false   # ставиш API ключ у Render Dashboard
      - key: WEBHOOK_URL
        value: https://trading-predictor.onrender.com
